# -*- coding: utf-8 -*-
"""Translation and Rotation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/141pySvskcPfm13ucBV8wlgLzVsj-ieFO
"""

import numpy as np
import matplotlib.pyplot as plt

A = np.array([3., 6., 9.])
B = np.array([6., 4., 2.])
C = np.array([3., 6., 9.])

xaxis = np.array([1., 0., 0.,])
yaxis = np.array([0., 1., 0.,])
zaxis = np.array([0., 0., 1.,])

I = np.array([[1., 0., 0.],
              [0., 1., 0.],
              [0., 0., 1.]])

R2= I + np.sin(2*np.pi/3)*yaxis + (1 - np.cos(2*np.pi/3))*np.dot(yaxis, yaxis)

def v_cross(v):
  return np.array([[0., -v[2], v[1]],
                   [v[2], 0., -v[0]],
                   [-v[1], v[0], 0.,]])

def rotate(ax, angle):
  v_x = v_cross(ax)
  return I + np.sin(angle)*v_x + (1 - np.cos(angle))*np.matmul(v_x, v_x)

r1 = np.matmul(rotate(xaxis, np.pi/4), A)
r2 = np.matmul(rotate(xaxis, np.pi/4), B)
r3 = np.matmul(rotate(xaxis, np.pi/4), C)

print(r1, r2, r3) #rotation around X axis

r21 = np.matmul(rotate(yaxis, 2*np.pi/3), r1)
r22 = np.matmul(rotate(yaxis, 2*np.pi/3), r2)
r23 = np.matmul(rotate(zaxis, 2*np.pi/3), r3)

print(r21, r22, r23) #rotation around Y axis

T = np.array([[1., 0., 0., 0.],
              [0., 1., 0., 0.],
              [0., 0., 1., -3.],
              [0., 0., 0., 1.]])

t1= np.array([r21[0],
              r21[1],
              r21[2],
              1.])
t2= np.array([r22[0],
              r22[1],
              r22[2],
              1.])
t3= np.array([r23[0],
              r23[1],
              r23[2],
              1.])

r21_t = np.matmul(T, t1)
r22_t = np.matmul(T, t2)
r23_t = np.matmul(T, t3)

print(r21_t, r22_t, r23_t) #translation along Z axis